---

name: publish post

on:
  push:
    master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install pipenv invoke
          pipenv --version
          pipenv install
      - name: Publish
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pipenv run inv github
